# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36271548da6ba1f1b19cf28b728e2b21870ee6b0eaa373ddf674ecc101cc3685b7959d55a0256c24ad6f4defa78b8ea759da1be9c4e5ccf15b29a675bb13f1a

test:
  secret_key_base: 6d000e46e257333bedf954c87fd1cb0455407d991d0f4f8c03065ed47f8ebcc709cde8927aabb7b74c85d7396865f27ff8a44ce3defae75faeacaa40dd9bc78d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
